### ISSUE TITLE
Trying to download the IWSLT17 test set causes a HTTP Error 404.

### ISSUE THREAD

**Issue by seanswyi** [mjpost/sacrebleu#128]
Hi. I'm trying to run the code `sacrebleu -t iwslt17 -l fr-en --echo src > ${INPUT_NAME}` and am getting the following error:

```
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/condaenv/lib/python3.7/site-packages/sacrebleu.py", line 1159, in download_test_set
    with urllib.request.urlopen(dataset) as f, open(tarball, 'wb') as out:
  File "/home/user/anaconda3/envs/condaenv/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/home/user/anaconda3/envs/condaenv/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/home/user/anaconda3/envs/condaenv/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/home/user/anaconda3/envs/condaenv/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/home/user/anaconda3/envs/condaenv/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/home/user/anaconda3/envs/condaenv/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

I've tried visiting the website https://wit3.fbk.eu/ and tried going to the URL in the SacreBLEU code (https://github.com/mjpost/sacrebleu/blob/5f14e99d1eb6a44cb14ee7bcd16ed68d5078efdd/sacrebleu/dataset.py#L537) and have noticed that the website is "under maintenance." Contacting Mauro Cettolo who I believe to be the website maintainer has led me to believe the new link is https://wit3.fbk.eu/2017-01-d.

Is there any way that this may be addressed and the code I initially tried to run will work? Thanks.

**Comment by ozancaglayan** [comment]
Not only that, the download links there seem to point to Google Drive instead of `wit3.fbk.eu`. This is bad, do you have further news on that @mjpost ?

**Comment by mjpost** [comment]
Has anyone tested these, e.g., to ensure they have the same checksums?

**Comment by ozancaglayan** [comment]
Yes I did it through the `__main__()` function of `dataset.py` (see the PR) which does this for every URL that has an md5 sum.
