### ISSUE TITLE
Short signature missing for TER (tercom tokenization)

### ISSUE THREAD

**Issue by zouharvi** [mjpost/sacrebleu#135]
It appears that the version string for TER is missing tercom tokenization abbreviation.

Without short:
```
$ python3 -m sacrebleu --metrics ter -i file1 file2 
TER+tok.tercom-nonorm-punct-noasian-uncased+version.1.4.14 = XXX
```

With short:
```
$ python3 -m sacrebleu --metrics ter --short -i file1 file2 
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/vilda/.local/lib/python3.8/site-packages/sacrebleu/__main__.py", line 27, in <module>
    main()
  File "/home/vilda/.local/lib/python3.8/site-packages/sacrebleu/sacrebleu.py", line 319, in main
    print(score.format(args.width, args.score_only, metric.signature))
  File "/home/vilda/.local/lib/python3.8/site-packages/sacrebleu/metrics/ter.py", line 80, in format
    prefix = "{}+{}".format(self.prefix, signature) if signature else self.prefix
  File "/home/vilda/.local/lib/python3.8/site-packages/sacrebleu/metrics/base.py", line 50, in __str__
    final_name = self._abbr[name] if self.short else name
KeyError: 'tok'
```

**Comment by ozancaglayan** [comment]
Hi, this is already fixed in `master` and will be available through the upcoming release.
