### ISSUE TITLE
ImportError: cannot import name 'tokenize_v14_international' from 'sacrebleu'

### ISSUE THREAD

**Issue by hsiang-lee** [mjpost/sacrebleu#183]
Traceback (most recent call last):
  File "C:\Users\leehsiang\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\leehsiang\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\projects\CodeGen\codegen_sources\model\translate.py", line 19, in <module>
    from codegen_sources.preprocessing.lang_processors.cpp_processor import CppProcessor
  File "D:\projects\CodeGen\codegen_sources\preprocessing\lang_processors\cpp_processor.py", line 7, in <module>
    from codegen_sources.preprocessing.lang_processors.tree_sitter_processor import (
  File "D:\projects\CodeGen\codegen_sources\preprocessing\lang_processors\tree_sitter_processor.py", line 8, in <module>
    from codegen_sources.preprocessing.lang_processors.tokenization_utils import (
  File "D:\projects\CodeGen\codegen_sources\preprocessing\lang_processors\tokenization_utils.py", line 8, in <module>
    from sacrebleu import tokenize_v14_international
ImportError: cannot import name 'tokenize_v14_international' from 'sacrebleu' (C:\Users\leehsiang\AppData\Local\Programs\Python\Python39\lib\site-packages\sacrebleu\__init__.py)

When I run facebook's CodeGen, an error occurred. Cannot import name  'tokenize_v14_international' from 'sacrebleu'. And I have successfully installed sacrebleu with "pip3 install sacrebleu".

Anybody could help me?

**Comment by martinpopel** [comment]
Note that CodeGen [requires](https://github.com/facebookresearch/CodeGen/blob/main/ci_requirements.txt#L12) `sacrebleu==1.2.11`. If you install that version of sacrbleu, everything should work.

An alternative would be to update that requirement to `sacrebleu>=2.1.0` and update [tokenization_utils.py](https://github.com/facebookresearch/CodeGen/blob/main/codegen_sources/preprocessing/lang_processors/tokenization_utils.py) so that instead of `from sacrebleu import tokenize_v14_international` it uses

```python
from sacrebleu.tokenizers.tokenizer_intl import TokenizerV14International
tokenize_v14_international = TokenizerV14International()
```

**Comment by hsiang-lee** [comment]
> 

Yeah! With sacrebleu 1.2.11, it works. Thank you very very much!!!
