### ISSUE TITLE
1.4.11 does not run when installed with pip

### ISSUE THREAD

**Issue by Khasir** [mjpost/sacrebleu#96]
I'm encountering a bug with installation. Steps to reproduce:

1. Create and activate a new virtual environment:  
`python -m venv test-env && source test-env/bin/activate`
2. Install sacrebleu from pip:
`pip install sacrebleu`
3. Run/import sacrebleu
`python -m sacrebleu`

Error message:
```Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/Users/kaz/envs/test/lib/python3.7/site-packages/sacrebleu/__init__.py", line 25, in <module>
    from .tokenizers import TOKENIZERS, DEFAULT_TOKENIZER
ModuleNotFoundError: No module named 'sacrebleu.tokenizers'

% ls /Users/kaz/envs/test/lib/python3.7/site-packages/sacrebleu/
__init__.py   __pycache__/  dataset.py    utils.py
__main__.py   compat.py     sacrebleu.py
```

I'm running Python version 3.7.7, if that helps.

**Comment by mjpost** [comment]
The v1.4.12 release fixes this. Thanks for reporting!
